### ISSUE TITLE
코드 리뷰를 드립니다 - 권혁우 튜터

### ISSUE THREAD

**Issue by hyokualexkwon** [rlaedous/todo-nextjs#1]
대연님 안녕하세요? 이번에 제출해주신 과제에 리뷰를 드릴게요.

---

- result에 대한 타이핑을 아예 상단의 results에 대해 미리 해두면 편할것 같아요. 그럼 콜백의 인자를 타이핑할 필요가 없겠어요. 뭐 지금은 이러나 저러나 큰 상관은 없겠지만요! https://github.com/rlaedous/todo-nextjs/blob/93d862cf6be25e1a5fc5fa79e5fdc15fd01da594/src/app/report/page.tsx#L35 `const resutls: Todo[] = await response.json()` 이렇게요~ https://github.com/rlaedous/todo-nextjs/blob/93d862cf6be25e1a5fc5fa79e5fdc15fd01da594/src/app/report/page.tsx#L13 

---

전반적으로 모난데 없이 잘 구현하셨네요. 피드백 드릴게 없어요! 많이 학습하고 여쭙고 다니시면서 크게 성장하고 계신것 같아요. 이대로만 잘 학습하시면 좋은 결과가 있을것 같습니다 :) 고생 많으셨어요!

**Comment by rlaedous** [comment]
감사합니다~!~!~!
